services:
  caddy:
    container_name: caddy
    image: caddy/caddy:2.8-alpine
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app_network

volumes:
  caddy_data:
  caddy_config:
