services:
  api:
    container_name: api
    image: alejandros2i/cochinillos-voladores
    environment:
      DATABASE_URL: "mysql://root:${MYSQL_PASSWORD}@db:3306/cochinillos"
      RUTA_UPLOADS: ${ RUTA_UPLOADS }
      MAIL: ${ MAIL }
      USUARIO_MAIL: ${ USUARIO_MAIL }
      CONTRA_MAIL: ${ CONTRA_MAIL }
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - uploads:/cochinillos-voladores/uploads
    networks:
        - app_network

  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: cochinillos
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
        - app_network

volumes:
  db:
  uploads:

networks:
  app_network:
