name: Compilar, probar y subir a producción

on:
  push:
    branches:
      - main

env:
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'codigo/cochinillos-voladores'

    steps:
    - name: Checkout codigo
      uses: actions/checkout@v4
    
    - name: Instalar rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Compilar y probar codigo
      run: |
          cargo build --verbose

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Iniciar sesión en docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Compilar y subir imagen docker
      uses: docker/bake-action@v4
      with:
        source: "{{defaultContext}}:codigo/cochinillos-voladores"
        push: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codigo
      uses: actions/checkout@v4

    - name: Iniciar sesión en docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Instalar sshpass
      run: sudo apt-get install sshpass

    - name: Copiar docker-compose.yml
      run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -o StrictHostKeyChecking=no codigo/cochinillos-voladores/docker-compose.yml root@${{ vars.DROPLET_IP }}:~

    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ vars.DROPLET_IP }}
        username: root
        password: ${{ secrets.DROPLET_PASSWORD }}
        script: |
          cd ~
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          docker-compose down
          docker-compose pull
          docker-compose up -d
